version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./Modelfile:/Modelfile
      - ollama_models:/root/.ollama
    entrypoint: >
      /bin/sh -c "
        ollama serve & 
        sleep 3 &&
        ollama create templanza -f /Modelfile &&
        wait"
    networks:
      - bot-net

  bot-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot-templanza
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    environment:
      LANGCHAIN4J_OLLAMA_BASE_URL: http://ollama:11434
    networks:
      - bot-net

volumes:
  ollama_models:

networks:
  bot-net:
    driver: bridge
